name: spacetelescope # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Explore the cosmos # 79 char long summary
description: |
  View the heavens at high and low magnification. Uses Unistra's API do obtain astronimical images at higher magnifications with a given right ascension and declination. For low magnification uses NASA starmap image of the night sky with constellations. Uses caltech's astronimical lookup API to allow you to search for specific objects eg NGC 100
icon: snap/gui/icon.png
website: https://github.com/forthtemple/spacetelescope/blob/main/README.md
source-code: https://github.com/forthtemple/spacetelescope

grade: stable #devel # # # must be '' to release into candidate/stable channels
confinement: strict #devmode # # # use 'strict' once you have the right plugs and slots

apps:
  spacetelescope:
    command: spacetelescope
    extensions: [gnome]

parts:
  telescope:
    source: .
    #source: ../../openworlddart/examplesecondtemple/
    source-type: local
    plugin: flutter
    flutter-target: lib/main.dart


